### ISSUE TITLE
running the app from uvicorns Python API does not work

### ISSUE THREAD

**Issue by pmeier** [bokeh/bokeh-fastapi#3]
`uvicorn test:app` in the terminal is equivalent to `python -c 'import uvicorn; uvicorn.run("test:app")'`. This works fine.

[Screencast from 2024-04-25 20-51-18.webm](https://github.com/bokeh/bokeh-fastapi/assets/6849766/51174bea-da19-419c-8cc8-57da1933a6f5)

However, for some reason, `python -c 'import uvicorn, test; uvicorn.run(test.app)'` does not. The server starts correctly and the WS is also connected. But for some reason no change is ever pushed back to the client.

[Screencast from 2024-04-25 20-59-07.webm](https://github.com/bokeh/bokeh-fastapi/assets/6849766/de00fb11-da34-4f41-9725-2b0db09d2430)

**Comment by pmeier** [comment]
It seems to be some import side effect. Importing the `test` module before running the server somehow breaks the functionality: `python -c 'import uvicorn, test; uvicorn.run("test:app")'`

**Comment by pmeier** [comment]
It seems to be caused by the fact that we instantiate `app` in the test module. If we wrap into a `make_app` function, we can do `python -c 'import uvicorn, test; uvicorn.run(test.make_app, factory=True)'`.

**Comment by pmeier** [comment]
Digging deeper, `uvicorn.run` internally uses `asyncio.run`. The app has to be created within this call rather than before to work correctly. The config is loaded at this point, which is why loading the app by string or creating it from the factory works.

**Comment by pmeier** [comment]
@philippjfr before I dig any deeper here, do you know of any side effects that the panel code could have that could cause a later execution of it by `asyncio.run` to somehow impede WS functionality?

**Comment by philippjfr** [comment]
>before I dig any deeper here, do you know of any side effects that the panel code could have that could cause a later execution of it by asyncio.run to somehow impede WS functionality?

I do not but will dig in a little more.

**Comment by pmeier** [comment]
Here is another pointer: async functions are not called when passing an app instance to `uvicorn.run`

```diff
diff --git a/test.py b/test.py
index 8efa324..8d31df6 100644
--- a/test.py
+++ b/test.py
@@ -20,6 +20,9 @@ def dispatch_fastapi(conn, events=None, msg=None):
 
 extra_socket_handlers[WSHandler] = dispatch_fastapi
 
+async def hello():
+    return pn.pane.Markdown("Hello!")
+
 
 def panel_app(doc):
     doc.on_event('document_ready', partial(pn.state._schedule_on_load, doc))
@@ -28,6 +31,7 @@ def panel_app(doc):
         slider = pn.widgets.IntSlider(start=0, end=10, value=5)
         out = pn.Column(
             pn.pane.Markdown('### ' + pn.rx('*') * slider),
+            hello,
             pn.state.session_info,
             pn.state.curdoc
         )
```

### `python -c 'import uvicorn; uvicorn.run("test:app")'`

![image](https://github.com/bokeh/bokeh-fastapi/assets/6849766/3bf751b0-afab-41da-9d6d-76c8cfe074bc)

### `python -c 'import uvicorn, test; uvicorn.run(test.app)'`

![image](https://github.com/bokeh/bokeh-fastapi/assets/6849766/0b488776-2edb-48b8-a0ba-09753e1e7787)

**Comment by pmeier** [comment]
The function call is correctly scheduled [here](https://github.com/holoviz/panel/blob/53b3a737abcac2cdbad0908cb0956174c88b65d5/panel/io/server.py#L179), but for some reason is never called.
